### ISSUE TITLE
dynamic_batching_test error

### ISSUE THREAD

**Issue by rnunziata** [deepmind/scalable_agent#19]
Trying to run: dynamic_batching_test and get the following error:
This error occurs several times I show only the last one.
.
```
----------------------------------------------------------------------
Ran 18 tests in 8.532s

OK
ERROR:tensorflow:Exception in QueueRunner: GetInputs operation was cancelled
	 [[Node: BatcherGetInputs = BatcherGetInputs[Toutput_list=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Batcher)]]
Exception in thread QueueRunnerThread-batcher-BatcherSetOutputs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rjn/.local/lib/python3.5/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/home/rjn/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1244, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/rjn/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: GetInputs operation was cancelled
	 [[Node: BatcherGetInputs = BatcherGetInputs[Toutput_list=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Batcher)]]

```

**Comment by lespeholt** [comment]
The tests actually run correctly (as you can see with OK). The output is from tests that tests error scenarios. Could probably be removed from the output.
