### ISSUE TITLE
Error running the experiment.py (Sonnet requires tensorflow_probability)

### ISSUE THREAD

**Issue by Draichi** [deepmind/scalable_agent#28]
Trying the Dockerfile via:

```
docker run --name scalable_agent scalable_agent
```

 and I'm having the following:

```
Traceback (most recent call last):
  File "experiment.py", line 31, in <module>
    import sonnet as snt
  File "/usr/local/lib/python2.7/dist-packages/sonnet/__init__.py", line 64, in <module>
    _ensure_dependency_available_at_version('tensorflow_probability', '0.4.0')
  File "/usr/local/lib/python2.7/dist-packages/sonnet/__init__.py", line 54, in _ensure_dependency_available_at_version
    package_name, min_version, pip_name, pip_name))
SystemError: Sonnet requires tensorflow_probability (minimum version 0.4.0) to be installed. If using pip, run `pip install tensorflow-probability` or `pip install tensorflow-probability-gpu`
```

but i've installed tensorflow-probability:
```
root@6475e1c7cae5:/scalable_agent# pip list installed
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
absl-py (0.6.1)
asn1crypto (0.24.0)
astor (0.7.1)
backports.weakref (1.0.post1)
contextlib2 (0.5.5)
cryptography (2.1.4)
DeepMind-Lab (1.0)
dm-sonnet (1.27)
enum34 (1.1.6)
funcsigs (1.0.2)
futures (3.2.0)
gast (0.2.0)
grpcio (1.17.1)
idna (2.6)
ipaddress (1.0.17)
keyring (10.6.0)
keyrings.alt (3.0)
Markdown (3.0.1)
mock (2.0.0)
numpy (1.15.4)
pbr (5.1.1)
Pillow (5.4.0)
pip (9.0.1)
protobuf (3.6.1)
pycrypto (2.6.1)
pygobject (3.26.1)
pyxdg (0.25)
SecretStorage (2.3.1)
semantic-version (2.6.0)
setuptools (39.0.1)
six (1.11.0)
tensorboard (1.9.0)
tensorflow (1.9.0)
tensorflow-probability (0.5.0)
termcolor (1.1.0)
Werkzeug (0.14.1)
wheel (0.30.0)
```

I also tried to run like this:
```
docker run -it scalable_agent:latest /bin/bash 
root@6475e1c7cae5:/scalable_agent# python experiment.py --num_actors=48 --batch_size=32
```

but got the same error...

OBS: I installed following this Dockerfile edit #16 

Anyone can give any tips??

**Comment by Huta2018** [comment]
This worked for me. Thanks.

**Comment by 4PMHHK** [comment]
Hi,Draichi ,I got the following similar error:

SystemError: Sonnet requires tensorflow (minimum version 1.8.0) to be installed. If using pip, run `pip install tensorflow` or `pip install tensorflow-gpu`

I tried to solve it such as above method , but it still have this error.
Can you help me? Thanks

**Comment by lespeholt** [comment]
I will recommend you to take a look at https://github.com/google-research/seed_rl/ which is a newer and improved implementation.
