### ISSUE TITLE
dynamic_batching_test failure

### ISSUE THREAD

**Issue by rnunziata** [deepmind/scalable_agent#3]
I have built the Dockerfile and have run all test  all work except ,,, each test in dyn batching test gets the following error.  Any thoughts.

```
python dynamic_batching_test.py
2018-07-02 19:44:17.724711: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
..2018-07-02 19:44:19.810578: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure at batcher.cc:285: Invalid argument: Batcher requires batch size 1 but was 2
2018-07-02 19:44:19.810614: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure: Cancelled: Compute was cancelled
.2018-07-02 19:44:20.826501: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure at batcher.cc:302: Invalid argument: Shapes of inputs much be equal. Shapes observed: [1], [1,1]
2018-07-02 19:44:20.826615: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure: Cancelled: Compute was cancelled
2018-07-02 19:44:20.826741: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure: Cancelled: Compute was cancelled
.2018-07-02 19:44:20.860884: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure at batcher.cc:347: Invalid argument: Invalid computation id. Id: 42
2018-07-02 19:44:20.860959: W tensorflow/core/framework/op_kernel.cc:1290] CtxFailure: Cancelled: Compute was cancelled
..ERROR:tensorflow:Exception in QueueRunner: GetInputs operation was cancelled
	 [[Node: BatcherGetInputs = BatcherGetInputs[Toutput_list=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Batcher)]]
Exception in thread QueueRunnerThread-batcher-BatcherSetOutputs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1244, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
CancelledError: GetInputs operation was cancelled
	 [[Node: BatcherGetInputs = BatcherGetInputs[Toutput_list=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Batcher)]]

```

**Comment by lespeholt** [comment]
Can you post the full output of running the command?

You are supposed to see these logs because there are tests for error scenarios. However, in the end you should see:
"Ran 18 tests in 8.152s

OK"
