### ISSUE TITLE
problem running the py_process_test

### ISSUE THREAD

**Issue by lljgreedyfox** [deepmind/scalable_agent#35]
When running the py_process_test.py with Python 3.6, it stucked with nothing output. However, the small test at the top of py_process.py passed.  It seems something wrong with the multiprocessing.Pipe(). But I still can not fix it.

Then I run  py_process_test.py with Python 2.7, I got the following error:

  ```
  File "/home/zixin/py27env/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/media/zixin/work/github/scalable_agent/py_process.py", line 89, in py_call
    raise result

ValueError: foo


..2019-04-19 10:06:34.488094: W tensorflow/core/framework/op_kernel.cc:1263] Invalid argument: exceptions.ValueError: foo
Traceback (most recent call last):

  File "/home/zixin/py27env/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/media/zixin/work/github/scalable_agent/py_process.py", line 89, in py_call
    raise result

ValueError: foo


....
----------------------------------------------------------------------
Ran 8 tests in 1.569s

OK
```

**Comment by calee88** [comment]
In my case, it stucked somewhere before it outputs Ran 8 tests in ...s. In your case, it says OK and it looks fine. I think the errors are intended.

**Comment by calee88** [comment]
I need to run it on Python3. When I ran it on Python3, it stucked without any output as you said. I upgraded tensorflow to version 1.14.0 and now it runs. But it still has some errors.
