### ISSUE TITLE
dynamic batching_test not terminating

### ISSUE THREAD

**Issue by ninji3** [deepmind/scalable_agent#36]
Hi
I currently have a problem with the dynamic batching.
I followed the installation in the Dockerfile step by step on a clean Ubuntu 18.04 distribution and the first problem I encounter is during the dynamic_batching_test.py, which does not seem to terminate at all. It it does not consume any CPU resources so it must be stuck waiting for some event. It also won't accept any manual interrupts.

Console output for "python dynamic_batching_test.py":
_______________________________________________________________________________________
EException in thread QueueRunnerThread-batcher-BatcherSetOutputs:
Traceback (most recent call last):
  File ""/usr/lib/python2.7/threading.py"", line 801, in __bootstrap_inner
    self.run()
  File ""/usr/lib/python2.7/threading.py"", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py"", line 268, in _run
    coord.request_stop(e)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py"", line 213, in request_stop
    six.reraise(*sys.exc_info())
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py"", line 252, in _run
    enqueue_callable()
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py"", line 1244, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File ""/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py"", line 1409, in _call_tf_sessionrun
    run_metadata)
CancelledError: GetInputs operation was cancelled
         [[Node: BatcherGetInputs = BatcherGetInputs[Toutput_list=[DT_INT32], _device=""/job:localhost/replica:0/task:0/device:CPU:0""](Batcher)]]

....
_______________________________________________________________________________________

Similarly, when running "python experiment.py --num_actors=5 --batch_size=32":
_______________________________________________________________________________________

2019-05-08 15:02:57.699728: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job local -> {0 -> localhost:39059}
--
2019-05-08 15:02:57.700277: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:334] Started server with target: grpc://localhost:39059
INFO:tensorflow:Using dynamic batching.
INFO:tensorflow:Creating actor 0 with level explore_goal_locations_small
INFO:tensorflow:Creating actor 1 with level explore_goal_locations_small
INFO:tensorflow:Creating actor 2 with level explore_goal_locations_small
INFO:tensorflow:Creating actor 3 with level explore_goal_locations_small
INFO:tensorflow:Creating MonitoredSession, is_chief True
INFO:tensorflow:Create CheckpointSaverHook.
WARNING:tensorflow:Issue encountered when serializing py_process_processes.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
PyProcess' object has no attribute 'name'
INFO:tensorflow:Starting all processes.
INFO:tensorflow:All processes started.
INFO:tensorflow:Graph was finalized.
2019-05-08 15:03:18.668394: I tensorflow/core/distributed_runtime/master_session.cc:1150] Start master session fb3984aaacbf6c88 with config: allow_soft_placement: true
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
^CProcess Process-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/home/julian/scalable_agent/py_process.py", line 134, in _worker_fn
serialized = in_.recv()
KeyboardInterrupt
Process Process-3:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
self.run()
Process Process-2:
Process Process-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
self.run()
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/home/julian/scalable_agent/py_process.py", line 134, in _worker_fn
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/home/julian/scalable_agent/py_process.py", line 134, in _worker_fn
serialized = in_.recv()
serialized = in_.recv()
self._target(*self._args, **self._kwargs)
File "/home/julian/scalable_agent/py_process.py", line 134, in _worker_fn
serialized = in_.recv()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
_______________________________________________________________________________________

Stuck during some multiprocessing routine in py_process.py. Disabling dynamic batching seems to work fine, while obviously having a much lower throughput. Until now, I could not figure out the reason for this and was able to confirm this issue on different machines and with colleagues.

**Comment by ninji3** [comment]
I think the code was not really meant to run purely on CPUs, running it with tensorflow-gpu works. I think this should be mentioned in the dockerfile.
