### ISSUE TITLE
incorporating other environments

### ISSUE THREAD

**Issue by esquires** [deepmind/scalable_agent#38]
I am trying to use IMPALA for a different environment than deepmind_lab but am having some diffficulty doing so. As a simple example, I tried incorporating CartPole with the following class:

```[python]

class PyProcessCartPole(object):

    def __init__(self):
      self._env = gym.make('CartPole-v0')

    def initial(self):
      initial_obs = self._env.reset()
      return initial_obs
    
    def render(self):
      return self._env.render()

    def step(self, action):
      obs, reward, is_done, _ = self._env.step(action)
      self._env.render()
      done = np.array(is_done)
      reward = np.float32(reward)
      
      if done:
        self._env.reset() 

      return reward, is_done, obs

    @staticmethod
    def _tensor_specs(method_name, unused_kwargs, constructor_kwargs):
      """Returns a nest of `TensorSpec` with the method's output specification."""
      observation_spec = tf.contrib.framework.TensorSpec([4], tf.uint8)

      if method_name == 'initial':
        # print("(environments.py) obs_specs are: ", observation_spec)
        return observation_spec
      elif method_name == 'step':
        return (
            tf.contrib.framework.TensorSpec([], tf.float32),
            tf.contrib.framework.TensorSpec([], tf.bool),
            observation_spec,
        )
      elif method_name == 'render':
        return observation_spec
```

Then I wrote a ``create_environment`` function to replace the current one:
```[python]
def create_environment_gym(*args, **kwargs):
  p = py_process.PyProcess(environments.PyProcessCartPole)
  return environments.FlowEnvironment(p.proxy)
```

I then get the following error:
```[bash]
Traceback (most recent call last):
  File "experiment.py", line 707, in <module>
    tf.app.run()
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "experiment.py", line 701, in main
    train(action_set, level_names)
  File "experiment.py", line 498, in train
    structure = build_actor(agent, env, level_names[0], action_set)
  File "experiment.py", line 237, in build_actor
    initial_agent_state)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 396, in __call__
    return self._call(*args, **kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 418, in _call
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 384, in __call__
    return self._call_func(args, kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 354, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 226, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "experiment.py", line 204, in _build
    outputs, core_state = self.unroll(actions, env_outputs, core_state)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/util.py", line 744, in eager_test
    return method(*args, **kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/util.py", line 864, in call_method
    out_ops = method(*args, **kwargs)
  File "experiment.py", line 211, in unroll
    torso_outputs = snt.BatchApply(self._torso)((actions, env_outputs))
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 396, in __call__
    return self._call(*args, **kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 418, in _call
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 384, in __call__
    return self._call_func(args, kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 354, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 226, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/basic.py", line 1085, in _build
    results = self._module(*merged_args, **merged_kwargs)
  File "experiment.py", line 145, in _torso
    reward, _, _, (frame, instruction) = env_output
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 477, in __iter__
    "Tensor objects are only iterable when eager execution is "
TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.

originally defined at:
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/basic.py", line 1053, in __init__
    super(BatchApply, self).__init__(name=name)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 180, in __init__
    custom_getter_=self._custom_getter)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 160, in make_template
    **kwargs)


originally defined at:
  File "experiment.py", line 496, in train
    agent = Agent(len(action_set))
  File "experiment.py", line 108, in __init__
    super(Agent, self).__init__(name='agent')
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/sonnet/python/modules/base.py", line 180, in __init__
    custom_getter_=self._custom_getter)
  File "/home/esquires/venvs/impala/local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 160, in make_template
    **kwargs)

```

In other words, in torso (in the Agent class), it can't convert ``env_output`` to ``reward, _, _, (frame, instruction)`` even though the length of ``env_output`` is 4. Can you help me understand what I might be doing wrong? Thanks!

**Comment by lespeholt** [comment]
env_output may be of length 4 but the 4th element can't be unpacked to (frame, instruction), so replace "(frame, instruction)" with "frame".
