### ISSUE TITLE
Having some issue running experiment.py in test mode. 

### ISSUE THREAD

**Issue by rnunziata** [deepmind/scalable_agent#4]
Having some issue running experiment.py in test mode. 

```
python experiment.py --mode=test --level_name=dmlab30 --dataset_path=[...] --test_num_episodes=10

I game_scripts/factories/skymaze_factory.lua:69] Generating levelMap with from seed 517459251
I game_scripts/factories/skymaze_factory.lua:74] 
.............
.............
.............
.......ffafg.
.......f.f.g.
.......fgfgg.
.......g.f...
.......fff...
.......g.....
.......g.....
.............
.............
.............

I game_scripts/factories/skymaze_factory.lua:69] Generating levelMap with from seed 74601396
I game_scripts/factories/skymaze_factory.lua:74] 
.........
.........
.........
...a.....
...h.....
...h.....
.........
.........
.........

I game_scripts/factories/skymaze_factory.lua:69] Generating levelMap with from seed 49392227
I game_scripts/factories/skymaze_factory.lua:74] 
.................
.kjhhg...........
.l.h.f...........
.kkijajmno.......
.m.n.o.p.q.......
.mmmmnnoop.......
...n.n.p.q.......
...nonrq.r.......
.....n.q.r.......
.ooooo.q.r.......
.o...p.r.r.......
.oop.qqqrr.......
...p.r...........
...qrr...........
.................
.................
.................

INFO:tensorflow:Mean episode return: 18.181818
INFO:tensorflow:Testing level: psychlab_arbitrary_visuomotor_mapping
[deepmind/engine/context.cc:1053] Check failed: result.ok()[modifyControl] - [image.load] - "[...]/1367.png" could not be read.
stack traceback:
	[C]: in function 'load'
	...eepmind_lab/baselab/game_scripts/datasets/reader.lua:38: in function 'getImage'
	...es/psychlab/arbitrary_visuomotor_mapping_factory.lua:435: in function 'addArray'
	...es/psychlab/arbitrary_visuomotor_mapping_factory.lua:349: in function 'mouseHoverCallback'
	.../game_scripts/factories/psychlab/point_and_click.lua:237: in function 'f'
	.../game_scripts/factories/psychlab/point_and_click.lua:260: in function 'onMouseOver'
	.../game_scripts/factories/psychlab/point_and_click.lua:406: in function 'step'
	.../baselab/game_scripts/factories/psychlab/factory.lua:81: in function 'modifyControl'
	...baselab/game_scripts/decorators/gadget_selection.lua:25: in function <...baselab/game_scripts/decorators/gadget_selection.lua:12>
	
```
image in 	dataset/1367.png  look to be ok and can be displayed.
	
Another issue: is that at Ctl-C: (never get control back - have to kill window)

```
^CProcess Process-27:
Traceback (most recent call last):
Process Process-30:
Process Process-20:
Traceback (most recent call last):
Traceback (most recent call last):
Process Process-12:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-5:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-3:
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
Process Process-25:
KeyboardInterrupt
Process Process-1:
Process Process-28:
Traceback (most recent call last):
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    serialized = in_.recv()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    serialized = in_.recv()
KeyboardInterrupt
Process Process-23:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    serialized = in_.recv()
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
    serialized = in_.recv()
KeyboardInterrupt
Process Process-22:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
Process Process-8:
Process Process-21:
Traceback (most recent call last):
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
Traceback (most recent call last):
Process Process-7:
Process Process-13:
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-6:
Process Process-17:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-4:
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Process-29:
Traceback (most recent call last):
    self.run()
    self.run()
Process Process-24:
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
Process Process-9:
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Process Process-26:
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
Process Process-18:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Traceback (most recent call last):
    serialized = in_.recv()
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
KeyboardInterrupt
    serialized = in_.recv()
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Traceback (most recent call last):
    serialized = in_.recv()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
KeyboardInterrupt
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
    serialized = in_.recv()
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
    serialized = in_.recv()
    serialized = in_.recv()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
  File "/scalable_agent/py_process.py", line 134, in _worker_fn
    serialized = in_.recv()
KeyboardInterrupt
KeyboardInterrupt
    serialized = in_.recv()
KeyboardInterrupt
```

**Comment by rnunziata** [comment]
yes ... this resolved the error...  it appears that the dataset is used only in a very small subset  of the test environments. Is this correct?

**Comment by lespeholt** [comment]
That is correct. Only for some psychlab levels (both test and train).
